using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DirectVKSender
{
    // @ https://gist.github.com/amgine/2395987
    // 윈도우 메시지도 복사해옴
    public static class WindowsMessage
    {
        public static string GetName(int Code)
        {
            if (MessageMap.ContainsKey(Code))
                return MessageMap[Code];

            return "Invalid Code";

        }

        static WindowsMessage()
        {
            MessageMap.Add(WM_NULL, "WM_NULL");
            MessageMap.Add(WM_CREATE, "WM_CREATE");
            MessageMap.Add(WM_DESTROY, "WM_DESTROY");
            MessageMap.Add(WM_MOVE, "WM_MOVE");
            MessageMap.Add(WM_SIZE, "WM_SIZE");
            MessageMap.Add(WM_ACTIVATE, "WM_ACTIVATE");
            MessageMap.Add(WM_SETFOCUS, "WM_SETFOCUS");
            MessageMap.Add(WM_KILLFOCUS, "WM_KILLFOCUS");
            MessageMap.Add(WM_ENABLE, "WM_ENABLE");
            MessageMap.Add(WM_SETREDRAW, "WM_SETREDRAW");
            MessageMap.Add(WM_SETTEXT, "WM_SETTEXT");
            MessageMap.Add(WM_GETTEXT, "WM_GETTEXT");
            MessageMap.Add(WM_GETTEXTLENGTH, "WM_GETTEXTLENGTH");
            MessageMap.Add(WM_PAINT, "WM_PAINT");
            MessageMap.Add(WM_CLOSE, "WM_CLOSE");
            MessageMap.Add(WM_QUERYENDSESSION, "WM_QUERYENDSESSION");
            MessageMap.Add(WM_QUERYOPEN, "WM_QUERYOPEN");
            MessageMap.Add(WM_ENDSESSION, "WM_ENDSESSION");
            MessageMap.Add(WM_QUIT, "WM_QUIT");
            MessageMap.Add(WM_ERASEBKGND, "WM_ERASEBKGND");
            MessageMap.Add(WM_SYSCOLORCHANGE, "WM_SYSCOLORCHANGE");
            MessageMap.Add(WM_SHOWWINDOW, "WM_SHOWWINDOW");
            MessageMap.Add(WM_WININICHANGE, "WM_WININICHANGE");
            MessageMap.Add(WM_DEVMODECHANGE, "WM_DEVMODECHANGE");
            MessageMap.Add(WM_ACTIVATEAPP, "WM_ACTIVATEAPP");
            MessageMap.Add(WM_FONTCHANGE, "WM_FONTCHANGE");
            MessageMap.Add(WM_TIMECHANGE, "WM_TIMECHANGE");
            MessageMap.Add(WM_CANCELMODE, "WM_CANCELMODE");
            MessageMap.Add(WM_SETCURSOR, "WM_SETCURSOR");
            MessageMap.Add(WM_MOUSEACTIVATE, "WM_MOUSEACTIVATE");
            MessageMap.Add(WM_CHILDACTIVATE, "WM_CHILDACTIVATE");
            MessageMap.Add(WM_QUEUESYNC, "WM_QUEUESYNC");
            MessageMap.Add(WM_GETMINMAXINFO, "WM_GETMINMAXINFO");
            MessageMap.Add(WM_PAINTICON, "WM_PAINTICON");
            MessageMap.Add(WM_ICONERASEBKGND, "WM_ICONERASEBKGND");
            MessageMap.Add(WM_NEXTDLGCTL, "WM_NEXTDLGCTL");
            MessageMap.Add(WM_SPOOLERSTATUS, "WM_SPOOLERSTATUS");
            MessageMap.Add(WM_DRAWITEM, "WM_DRAWITEM");
            MessageMap.Add(WM_MEASUREITEM, "WM_MEASUREITEM");
            MessageMap.Add(WM_DELETEITEM, "WM_DELETEITEM");
            MessageMap.Add(WM_VKEYTOITEM, "WM_VKEYTOITEM");
            MessageMap.Add(WM_CHARTOITEM, "WM_CHARTOITEM");
            MessageMap.Add(WM_SETFONT, "WM_SETFONT");
            MessageMap.Add(WM_GETFONT, "WM_GETFONT");
            MessageMap.Add(WM_SETHOTKEY, "WM_SETHOTKEY");
            MessageMap.Add(WM_GETHOTKEY, "WM_GETHOTKEY");
            MessageMap.Add(WM_QUERYDRAGICON, "WM_QUERYDRAGICON");
            MessageMap.Add(WM_COMPAREITEM, "WM_COMPAREITEM");
            MessageMap.Add(WM_GETOBJECT, "WM_GETOBJECT");
            MessageMap.Add(WM_COMPACTING, "WM_COMPACTING");
            MessageMap.Add(WM_COMMNOTIFY, "WM_COMMNOTIFY");
            MessageMap.Add(WM_WINDOWPOSCHANGING, "WM_WINDOWPOSCHANGING");
            MessageMap.Add(WM_WINDOWPOSCHANGED, "WM_WINDOWPOSCHANGED");
            MessageMap.Add(WM_POWER, "WM_POWER");
            MessageMap.Add(WM_COPYDATA, "WM_COPYDATA");
            MessageMap.Add(WM_CANCELJOURNAL, "WM_CANCELJOURNAL");
            MessageMap.Add(WM_NOTIFY, "WM_NOTIFY");
            MessageMap.Add(WM_INPUTLANGCHANGEREQUEST, "WM_INPUTLANGCHANGEREQUEST");
            MessageMap.Add(WM_INPUTLANGCHANGE, "WM_INPUTLANGCHANGE");
            MessageMap.Add(WM_TCARD, "WM_TCARD");
            MessageMap.Add(WM_HELP, "WM_HELP");
            MessageMap.Add(WM_USERCHANGED, "WM_USERCHANGED");
            MessageMap.Add(WM_NOTIFYFORMAT, "WM_NOTIFYFORMAT");
            MessageMap.Add(WM_CONTEXTMENU, "WM_CONTEXTMENU");
            MessageMap.Add(WM_STYLECHANGING, "WM_STYLECHANGING");
            MessageMap.Add(WM_STYLECHANGED, "WM_STYLECHANGED");
            MessageMap.Add(WM_DISPLAYCHANGE, "WM_DISPLAYCHANGE");
            MessageMap.Add(WM_GETICON, "WM_GETICON");
            MessageMap.Add(WM_SETICON, "WM_SETICON");
            MessageMap.Add(WM_NCCREATE, "WM_NCCREATE");
            MessageMap.Add(WM_NCDESTROY, "WM_NCDESTROY");
            MessageMap.Add(WM_NCCALCSIZE, "WM_NCCALCSIZE");
            MessageMap.Add(WM_NCHITTEST, "WM_NCHITTEST");
            MessageMap.Add(WM_NCPAINT, "WM_NCPAINT");
            MessageMap.Add(WM_NCACTIVATE, "WM_NCACTIVATE");
            MessageMap.Add(WM_GETDLGCODE, "WM_GETDLGCODE");
            MessageMap.Add(WM_SYNCPAINT, "WM_SYNCPAINT");
            MessageMap.Add(WM_NCMOUSEMOVE, "WM_NCMOUSEMOVE");
            MessageMap.Add(WM_NCLBUTTONDOWN, "WM_NCLBUTTONDOWN");
            MessageMap.Add(WM_NCLBUTTONUP, "WM_NCLBUTTONUP");
            MessageMap.Add(WM_NCLBUTTONDBLCLK, "WM_NCLBUTTONDBLCLK");
            MessageMap.Add(WM_NCRBUTTONDOWN, "WM_NCRBUTTONDOWN");
            MessageMap.Add(WM_NCRBUTTONUP, "WM_NCRBUTTONUP");
            MessageMap.Add(WM_NCRBUTTONDBLCLK, "WM_NCRBUTTONDBLCLK");
            MessageMap.Add(WM_NCMBUTTONDOWN, "WM_NCMBUTTONDOWN");
            MessageMap.Add(WM_NCMBUTTONUP, "WM_NCMBUTTONUP");
            MessageMap.Add(WM_NCMBUTTONDBLCLK, "WM_NCMBUTTONDBLCLK");
            MessageMap.Add(WM_NCXBUTTONDOWN, "WM_NCXBUTTONDOWN");
            MessageMap.Add(WM_NCXBUTTONUP, "WM_NCXBUTTONUP");
            MessageMap.Add(WM_NCXBUTTONDBLCLK, "WM_NCXBUTTONDBLCLK");
            MessageMap.Add(WM_INPUT_DEVICE_CHANGE, "WM_INPUT_DEVICE_CHANGE");
            MessageMap.Add(WM_INPUT, "WM_INPUT");
            MessageMap.Add(WM_KEYDOWN, "WM_KEYDOWN");
            MessageMap.Add(WM_KEYUP, "WM_KEYUP");
            MessageMap.Add(WM_CHAR, "WM_CHAR");
            MessageMap.Add(WM_DEADCHAR, "WM_DEADCHAR");
            MessageMap.Add(WM_SYSKEYDOWN, "WM_SYSKEYDOWN");
            MessageMap.Add(WM_SYSKEYUP, "WM_SYSKEYUP");
            MessageMap.Add(WM_SYSCHAR, "WM_SYSCHAR");
            MessageMap.Add(WM_SYSDEADCHAR, "WM_SYSDEADCHAR");
            MessageMap.Add(WM_UNICHAR, "WM_UNICHAR");
            MessageMap.Add(WM_IME_STARTCOMPOSITION, "WM_IME_STARTCOMPOSITION");
            MessageMap.Add(WM_IME_ENDCOMPOSITION, "WM_IME_ENDCOMPOSITION");
            MessageMap.Add(WM_IME_COMPOSITION, "WM_IME_COMPOSITION");
            MessageMap.Add(WM_INITDIALOG, "WM_INITDIALOG");
            MessageMap.Add(WM_COMMAND, "WM_COMMAND");
            MessageMap.Add(WM_SYSCOMMAND, "WM_SYSCOMMAND");
            MessageMap.Add(WM_TIMER, "WM_TIMER");
            MessageMap.Add(WM_HSCROLL, "WM_HSCROLL");
            MessageMap.Add(WM_VSCROLL, "WM_VSCROLL");
            MessageMap.Add(WM_INITMENU, "WM_INITMENU");
            MessageMap.Add(WM_INITMENUPOPUP, "WM_INITMENUPOPUP");
            MessageMap.Add(WM_MENUSELECT, "WM_MENUSELECT");
            MessageMap.Add(WM_MENUCHAR, "WM_MENUCHAR");
            MessageMap.Add(WM_ENTERIDLE, "WM_ENTERIDLE");
            MessageMap.Add(WM_MENURBUTTONUP, "WM_MENURBUTTONUP");
            MessageMap.Add(WM_MENUDRAG, "WM_MENUDRAG");
            MessageMap.Add(WM_MENUGETOBJECT, "WM_MENUGETOBJECT");
            MessageMap.Add(WM_UNINITMENUPOPUP, "WM_UNINITMENUPOPUP");
            MessageMap.Add(WM_MENUCOMMAND, "WM_MENUCOMMAND");
            MessageMap.Add(WM_CHANGEUISTATE, "WM_CHANGEUISTATE");
            MessageMap.Add(WM_UPDATEUISTATE, "WM_UPDATEUISTATE");
            MessageMap.Add(WM_QUERYUISTATE, "WM_QUERYUISTATE");
            MessageMap.Add(WM_CTLCOLORMSGBOX, "WM_CTLCOLORMSGBOX");
            MessageMap.Add(WM_CTLCOLOREDIT, "WM_CTLCOLOREDIT");
            MessageMap.Add(WM_CTLCOLORLISTBOX, "WM_CTLCOLORLISTBOX");
            MessageMap.Add(WM_CTLCOLORBTN, "WM_CTLCOLORBTN");
            MessageMap.Add(WM_CTLCOLORDLG, "WM_CTLCOLORDLG");
            MessageMap.Add(WM_CTLCOLORSCROLLBAR, "WM_CTLCOLORSCROLLBAR");
            MessageMap.Add(WM_CTLCOLORSTATIC, "WM_CTLCOLORSTATIC");
            MessageMap.Add(MN_GETHMENU, "MN_GETHMENU");
            MessageMap.Add(WM_MOUSEMOVE, "WM_MOUSEMOVE");
            MessageMap.Add(WM_LBUTTONDOWN, "WM_LBUTTONDOWN");
            MessageMap.Add(WM_LBUTTONUP, "WM_LBUTTONUP");
            MessageMap.Add(WM_LBUTTONDBLCLK, "WM_LBUTTONDBLCLK");
            MessageMap.Add(WM_RBUTTONDOWN, "WM_RBUTTONDOWN");
            MessageMap.Add(WM_RBUTTONUP, "WM_RBUTTONUP");
            MessageMap.Add(WM_RBUTTONDBLCLK, "WM_RBUTTONDBLCLK");
            MessageMap.Add(WM_MBUTTONDOWN, "WM_MBUTTONDOWN");
            MessageMap.Add(WM_MBUTTONUP, "WM_MBUTTONUP");
            MessageMap.Add(WM_MBUTTONDBLCLK, "WM_MBUTTONDBLCLK");
            MessageMap.Add(WM_MOUSEWHEEL, "WM_MOUSEWHEEL");
            MessageMap.Add(WM_XBUTTONDOWN, "WM_XBUTTONDOWN");
            MessageMap.Add(WM_XBUTTONUP, "WM_XBUTTONUP");
            MessageMap.Add(WM_XBUTTONDBLCLK, "WM_XBUTTONDBLCLK");
            MessageMap.Add(WM_MOUSEHWHEEL, "WM_MOUSEHWHEEL");
            MessageMap.Add(WM_PARENTNOTIFY, "WM_PARENTNOTIFY");
            MessageMap.Add(WM_ENTERMENULOOP, "WM_ENTERMENULOOP");
            MessageMap.Add(WM_EXITMENULOOP, "WM_EXITMENULOOP");
            MessageMap.Add(WM_NEXTMENU, "WM_NEXTMENU");
            MessageMap.Add(WM_SIZING, "WM_SIZING");
            MessageMap.Add(WM_CAPTURECHANGED, "WM_CAPTURECHANGED");
            MessageMap.Add(WM_MOVING, "WM_MOVING");
            MessageMap.Add(WM_POWERBROADCAST, "WM_POWERBROADCAST");
            MessageMap.Add(WM_DEVICECHANGE, "WM_DEVICECHANGE");
            MessageMap.Add(WM_MDICREATE, "WM_MDICREATE");
            MessageMap.Add(WM_MDIDESTROY, "WM_MDIDESTROY");
            MessageMap.Add(WM_MDIACTIVATE, "WM_MDIACTIVATE");
            MessageMap.Add(WM_MDIRESTORE, "WM_MDIRESTORE");
            MessageMap.Add(WM_MDINEXT, "WM_MDINEXT");
            MessageMap.Add(WM_MDIMAXIMIZE, "WM_MDIMAXIMIZE");
            MessageMap.Add(WM_MDITILE, "WM_MDITILE");
            MessageMap.Add(WM_MDICASCADE, "WM_MDICASCADE");
            MessageMap.Add(WM_MDIICONARRANGE, "WM_MDIICONARRANGE");
            MessageMap.Add(WM_MDIGETACTIVE, "WM_MDIGETACTIVE");
            MessageMap.Add(WM_MDISETMENU, "WM_MDISETMENU");
            MessageMap.Add(WM_ENTERSIZEMOVE, "WM_ENTERSIZEMOVE");
            MessageMap.Add(WM_EXITSIZEMOVE, "WM_EXITSIZEMOVE");
            MessageMap.Add(WM_DROPFILES, "WM_DROPFILES");
            MessageMap.Add(WM_MDIREFRESHMENU, "WM_MDIREFRESHMENU");
            MessageMap.Add(WM_IME_SETCONTEXT, "WM_IME_SETCONTEXT");
            MessageMap.Add(WM_IME_NOTIFY, "WM_IME_NOTIFY");
            MessageMap.Add(WM_IME_CONTROL, "WM_IME_CONTROL");
            MessageMap.Add(WM_IME_COMPOSITIONFULL, "WM_IME_COMPOSITIONFULL");
            MessageMap.Add(WM_IME_SELECT, "WM_IME_SELECT");
            MessageMap.Add(WM_IME_CHAR, "WM_IME_CHAR");
            MessageMap.Add(WM_IME_REQUEST, "WM_IME_REQUEST");
            MessageMap.Add(WM_IME_KEYDOWN, "WM_IME_KEYDOWN");
            MessageMap.Add(WM_IME_KEYUP, "WM_IME_KEYUP");
            MessageMap.Add(WM_MOUSEHOVER, "WM_MOUSEHOVER");
            MessageMap.Add(WM_MOUSELEAVE, "WM_MOUSELEAVE");
            MessageMap.Add(WM_NCMOUSEHOVER, "WM_NCMOUSEHOVER");
            MessageMap.Add(WM_NCMOUSELEAVE, "WM_NCMOUSELEAVE");
            MessageMap.Add(WM_WTSSESSION_CHANGE, "WM_WTSSESSION_CHANGE");
            MessageMap.Add(WM_TABLET_FIRST, "WM_TABLET_FIRST");
            MessageMap.Add(WM_TABLET_LAST, "WM_TABLET_LAST");
            MessageMap.Add(WM_CUT, "WM_CUT");
            MessageMap.Add(WM_COPY, "WM_COPY");
            MessageMap.Add(WM_PASTE, "WM_PASTE");
            MessageMap.Add(WM_CLEAR, "WM_CLEAR");
            MessageMap.Add(WM_UNDO, "WM_UNDO");
            MessageMap.Add(WM_RENDERFORMAT, "WM_RENDERFORMAT");
            MessageMap.Add(WM_RENDERALLFORMATS, "WM_RENDERALLFORMATS");
            MessageMap.Add(WM_DESTROYCLIPBOARD, "WM_DESTROYCLIPBOARD");
            MessageMap.Add(WM_DRAWCLIPBOARD, "WM_DRAWCLIPBOARD");
            MessageMap.Add(WM_PAINTCLIPBOARD, "WM_PAINTCLIPBOARD");
            MessageMap.Add(WM_VSCROLLCLIPBOARD, "WM_VSCROLLCLIPBOARD");
            MessageMap.Add(WM_SIZECLIPBOARD, "WM_SIZECLIPBOARD");
            MessageMap.Add(WM_ASKCBFORMATNAME, "WM_ASKCBFORMATNAME");
            MessageMap.Add(WM_CHANGECBCHAIN, "WM_CHANGECBCHAIN");
            MessageMap.Add(WM_HSCROLLCLIPBOARD, "WM_HSCROLLCLIPBOARD");
            MessageMap.Add(WM_QUERYNEWPALETTE, "WM_QUERYNEWPALETTE");
            MessageMap.Add(WM_PALETTEISCHANGING, "WM_PALETTEISCHANGING");
            MessageMap.Add(WM_PALETTECHANGED, "WM_PALETTECHANGED");
            MessageMap.Add(WM_HOTKEY, "WM_HOTKEY");
            MessageMap.Add(WM_PRINT, "WM_PRINT");
            MessageMap.Add(WM_PRINTCLIENT, "WM_PRINTCLIENT");
            MessageMap.Add(WM_APPCOMMAND, "WM_APPCOMMAND");
            MessageMap.Add(WM_THEMECHANGED, "WM_THEMECHANGED");
            MessageMap.Add(WM_CLIPBOARDUPDATE, "WM_CLIPBOARDUPDATE");
            MessageMap.Add(WM_DWMCOMPOSITIONCHANGED, "WM_DWMCOMPOSITIONCHANGED");
            MessageMap.Add(WM_DWMNCRENDERINGCHANGED, "WM_DWMNCRENDERINGCHANGED");
            MessageMap.Add(WM_DWMCOLORIZATIONCOLORCHANGED, "WM_DWMCOLORIZATIONCOLORCHANGED");
            MessageMap.Add(WM_DWMWINDOWMAXIMIZEDCHANGE, "WM_DWMWINDOWMAXIMIZEDCHANGE");
            MessageMap.Add(WM_GETTITLEBARINFOEX, "WM_GETTITLEBARINFOEX");
            MessageMap.Add(WM_HANDHELDFIRST, "WM_HANDHELDFIRST");
            MessageMap.Add(WM_HANDHELDLAST, "WM_HANDHELDLAST");
            MessageMap.Add(WM_AFXFIRST, "WM_AFXFIRST");
            MessageMap.Add(WM_AFXLAST, "WM_AFXLAST");
            MessageMap.Add(WM_PENWINFIRST, "WM_PENWINFIRST");
            MessageMap.Add(WM_PENWINLAST, "WM_PENWINLAST");
            MessageMap.Add(WM_APP, "WM_APP");
            MessageMap.Add(WM_USER, "WM_USER");
            MessageMap.Add(WM_REFLECT, "WM_REFLECT");
        }

        private static readonly Dictionary<int, string> MessageMap = new Dictionary<int, string>();

        // ============================================================================================

        public const int WM_NULL = 0x0000;
        public const int WM_CREATE = 0x0001;
        public const int WM_DESTROY = 0x0002;
        public const int WM_MOVE = 0x0003;
        public const int WM_SIZE = 0x0005;
        public const int WM_ACTIVATE = 0x0006;
        public const int WM_SETFOCUS = 0x0007;
        public const int WM_KILLFOCUS = 0x0008;
        public const int WM_ENABLE = 0x000A;
        public const int WM_SETREDRAW = 0x000B;
        public const int WM_SETTEXT = 0x000C;
        public const int WM_GETTEXT = 0x000D;
        public const int WM_GETTEXTLENGTH = 0x000E;
        public const int WM_PAINT = 0x000F;
        public const int WM_CLOSE = 0x0010;
        public const int WM_QUERYENDSESSION = 0x0011;
        public const int WM_QUERYOPEN = 0x0013;
        public const int WM_ENDSESSION = 0x0016;
        public const int WM_QUIT = 0x0012;
        public const int WM_ERASEBKGND = 0x0014;
        public const int WM_SYSCOLORCHANGE = 0x0015;
        public const int WM_SHOWWINDOW = 0x0018;
        public const int WM_WININICHANGE = 0x001A;
        public const int WM_DEVMODECHANGE = 0x001B;
        public const int WM_ACTIVATEAPP = 0x001C;
        public const int WM_FONTCHANGE = 0x001D;
        public const int WM_TIMECHANGE = 0x001E;
        public const int WM_CANCELMODE = 0x001F;
        public const int WM_SETCURSOR = 0x0020;
        public const int WM_MOUSEACTIVATE = 0x0021;
        public const int WM_CHILDACTIVATE = 0x0022;
        public const int WM_QUEUESYNC = 0x0023;
        public const int WM_GETMINMAXINFO = 0x0024;
        public const int WM_PAINTICON = 0x0026;
        public const int WM_ICONERASEBKGND = 0x0027;
        public const int WM_NEXTDLGCTL = 0x0028;
        public const int WM_SPOOLERSTATUS = 0x002A;
        public const int WM_DRAWITEM = 0x002B;
        public const int WM_MEASUREITEM = 0x002C;
        public const int WM_DELETEITEM = 0x002D;
        public const int WM_VKEYTOITEM = 0x002E;
        public const int WM_CHARTOITEM = 0x002F;
        public const int WM_SETFONT = 0x0030;
        public const int WM_GETFONT = 0x0031;
        public const int WM_SETHOTKEY = 0x0032;
        public const int WM_GETHOTKEY = 0x0033;
        public const int WM_QUERYDRAGICON = 0x0037;
        public const int WM_COMPAREITEM = 0x0039;
        public const int WM_GETOBJECT = 0x003D;
        public const int WM_COMPACTING = 0x0041;
        public const int WM_COMMNOTIFY = 0x0044;
        public const int WM_WINDOWPOSCHANGING = 0x0046;
        public const int WM_WINDOWPOSCHANGED = 0x0047;
        public const int WM_POWER = 0x0048;
        public const int WM_COPYDATA = 0x004A;
        public const int WM_CANCELJOURNAL = 0x004B;
        public const int WM_NOTIFY = 0x004E;
        public const int WM_INPUTLANGCHANGEREQUEST = 0x0050;
        public const int WM_INPUTLANGCHANGE = 0x0051;
        public const int WM_TCARD = 0x0052;
        public const int WM_HELP = 0x0053;
        public const int WM_USERCHANGED = 0x0054;
        public const int WM_NOTIFYFORMAT = 0x0055;
        public const int WM_CONTEXTMENU = 0x007B;
        public const int WM_STYLECHANGING = 0x007C;
        public const int WM_STYLECHANGED = 0x007D;
        public const int WM_DISPLAYCHANGE = 0x007E;
        public const int WM_GETICON = 0x007F;
        public const int WM_SETICON = 0x0080;
        public const int WM_NCCREATE = 0x0081;
        public const int WM_NCDESTROY = 0x0082;
        public const int WM_NCCALCSIZE = 0x0083;
        public const int WM_NCHITTEST = 0x0084;
        public const int WM_NCPAINT = 0x0085;
        public const int WM_NCACTIVATE = 0x0086;
        public const int WM_GETDLGCODE = 0x0087;
        public const int WM_SYNCPAINT = 0x0088;
        public const int WM_NCMOUSEMOVE = 0x00A0;
        public const int WM_NCLBUTTONDOWN = 0x00A1;
        public const int WM_NCLBUTTONUP = 0x00A2;
        public const int WM_NCLBUTTONDBLCLK = 0x00A3;
        public const int WM_NCRBUTTONDOWN = 0x00A4;
        public const int WM_NCRBUTTONUP = 0x00A5;
        public const int WM_NCRBUTTONDBLCLK = 0x00A6;
        public const int WM_NCMBUTTONDOWN = 0x00A7;
        public const int WM_NCMBUTTONUP = 0x00A8;
        public const int WM_NCMBUTTONDBLCLK = 0x00A9;
        public const int WM_NCXBUTTONDOWN = 0x00AB;
        public const int WM_NCXBUTTONUP = 0x00AC;
        public const int WM_NCXBUTTONDBLCLK = 0x00AD;
        public const int WM_INPUT_DEVICE_CHANGE = 0x00FE;
        public const int WM_INPUT = 0x00FF;
        public const int WM_KEYDOWN = 0x0100;
        public const int WM_KEYUP = 0x0101;
        public const int WM_CHAR = 0x0102;
        public const int WM_DEADCHAR = 0x0103;
        public const int WM_SYSKEYDOWN = 0x0104;
        public const int WM_SYSKEYUP = 0x0105;
        public const int WM_SYSCHAR = 0x0106;
        public const int WM_SYSDEADCHAR = 0x0107;
        public const int WM_UNICHAR = 0x0109;
        public const int WM_IME_STARTCOMPOSITION = 0x010D;
        public const int WM_IME_ENDCOMPOSITION = 0x010E;
        public const int WM_IME_COMPOSITION = 0x010F;
        public const int WM_INITDIALOG = 0x0110;
        public const int WM_COMMAND = 0x0111;
        public const int WM_SYSCOMMAND = 0x0112;
        public const int WM_TIMER = 0x0113;
        public const int WM_HSCROLL = 0x0114;
        public const int WM_VSCROLL = 0x0115;
        public const int WM_INITMENU = 0x0116;
        public const int WM_INITMENUPOPUP = 0x0117;
        public const int WM_MENUSELECT = 0x011F;
        public const int WM_MENUCHAR = 0x0120;
        public const int WM_ENTERIDLE = 0x0121;
        public const int WM_MENURBUTTONUP = 0x0122;
        public const int WM_MENUDRAG = 0x0123;
        public const int WM_MENUGETOBJECT = 0x0124;
        public const int WM_UNINITMENUPOPUP = 0x0125;
        public const int WM_MENUCOMMAND = 0x0126;
        public const int WM_CHANGEUISTATE = 0x0127;
        public const int WM_UPDATEUISTATE = 0x0128;
        public const int WM_QUERYUISTATE = 0x0129;
        public const int WM_CTLCOLORMSGBOX = 0x0132;
        public const int WM_CTLCOLOREDIT = 0x0133;
        public const int WM_CTLCOLORLISTBOX = 0x0134;
        public const int WM_CTLCOLORBTN = 0x0135;
        public const int WM_CTLCOLORDLG = 0x0136;
        public const int WM_CTLCOLORSCROLLBAR = 0x0137;
        public const int WM_CTLCOLORSTATIC = 0x0138;
        public const int MN_GETHMENU = 0x01E1;
        public const int WM_MOUSEMOVE = 0x0200;
        public const int WM_LBUTTONDOWN = 0x0201;
        public const int WM_LBUTTONUP = 0x0202;
        public const int WM_LBUTTONDBLCLK = 0x0203;
        public const int WM_RBUTTONDOWN = 0x0204;
        public const int WM_RBUTTONUP = 0x0205;
        public const int WM_RBUTTONDBLCLK = 0x0206;
        public const int WM_MBUTTONDOWN = 0x0207;
        public const int WM_MBUTTONUP = 0x0208;
        public const int WM_MBUTTONDBLCLK = 0x0209;
        public const int WM_MOUSEWHEEL = 0x020A;
        public const int WM_XBUTTONDOWN = 0x020B;
        public const int WM_XBUTTONUP = 0x020C;
        public const int WM_XBUTTONDBLCLK = 0x020D;
        public const int WM_MOUSEHWHEEL = 0x020E;
        public const int WM_PARENTNOTIFY = 0x0210;
        public const int WM_ENTERMENULOOP = 0x0211;
        public const int WM_EXITMENULOOP = 0x0212;
        public const int WM_NEXTMENU = 0x0213;
        public const int WM_SIZING = 0x0214;
        public const int WM_CAPTURECHANGED = 0x0215;
        public const int WM_MOVING = 0x0216;
        public const int WM_POWERBROADCAST = 0x0218;
        public const int WM_DEVICECHANGE = 0x0219;
        public const int WM_MDICREATE = 0x0220;
        public const int WM_MDIDESTROY = 0x0221;
        public const int WM_MDIACTIVATE = 0x0222;
        public const int WM_MDIRESTORE = 0x0223;
        public const int WM_MDINEXT = 0x0224;
        public const int WM_MDIMAXIMIZE = 0x0225;
        public const int WM_MDITILE = 0x0226;
        public const int WM_MDICASCADE = 0x0227;
        public const int WM_MDIICONARRANGE = 0x0228;
        public const int WM_MDIGETACTIVE = 0x0229;
        public const int WM_MDISETMENU = 0x0230;
        public const int WM_ENTERSIZEMOVE = 0x0231;
        public const int WM_EXITSIZEMOVE = 0x0232;
        public const int WM_DROPFILES = 0x0233;
        public const int WM_MDIREFRESHMENU = 0x0234;
        public const int WM_IME_SETCONTEXT = 0x0281;
        public const int WM_IME_NOTIFY = 0x0282;
        public const int WM_IME_CONTROL = 0x0283;
        public const int WM_IME_COMPOSITIONFULL = 0x0284;
        public const int WM_IME_SELECT = 0x0285;
        public const int WM_IME_CHAR = 0x0286;
        public const int WM_IME_REQUEST = 0x0288;
        public const int WM_IME_KEYDOWN = 0x0290;
        public const int WM_IME_KEYUP = 0x0291;
        public const int WM_MOUSEHOVER = 0x02A1;
        public const int WM_MOUSELEAVE = 0x02A3;
        public const int WM_NCMOUSEHOVER = 0x02A0;
        public const int WM_NCMOUSELEAVE = 0x02A2;
        public const int WM_WTSSESSION_CHANGE = 0x02B1;
        public const int WM_TABLET_FIRST = 0x02c0;
        public const int WM_TABLET_LAST = 0x02df;
        public const int WM_CUT = 0x0300;
        public const int WM_COPY = 0x0301;
        public const int WM_PASTE = 0x0302;
        public const int WM_CLEAR = 0x0303;
        public const int WM_UNDO = 0x0304;
        public const int WM_RENDERFORMAT = 0x0305;
        public const int WM_RENDERALLFORMATS = 0x0306;
        public const int WM_DESTROYCLIPBOARD = 0x0307;
        public const int WM_DRAWCLIPBOARD = 0x0308;
        public const int WM_PAINTCLIPBOARD = 0x0309;
        public const int WM_VSCROLLCLIPBOARD = 0x030A;
        public const int WM_SIZECLIPBOARD = 0x030B;
        public const int WM_ASKCBFORMATNAME = 0x030C;
        public const int WM_CHANGECBCHAIN = 0x030D;
        public const int WM_HSCROLLCLIPBOARD = 0x030E;
        public const int WM_QUERYNEWPALETTE = 0x030F;
        public const int WM_PALETTEISCHANGING = 0x0310;
        public const int WM_PALETTECHANGED = 0x0311;
        public const int WM_HOTKEY = 0x0312;
        public const int WM_PRINT = 0x0317;
        public const int WM_PRINTCLIENT = 0x0318;
        public const int WM_APPCOMMAND = 0x0319;
        public const int WM_THEMECHANGED = 0x031A;
        public const int WM_CLIPBOARDUPDATE = 0x031D;
        public const int WM_DWMCOMPOSITIONCHANGED = 0x031E;
        public const int WM_DWMNCRENDERINGCHANGED = 0x031F;
        public const int WM_DWMCOLORIZATIONCOLORCHANGED = 0x0320;
        public const int WM_DWMWINDOWMAXIMIZEDCHANGE = 0x0321;
        public const int WM_GETTITLEBARINFOEX = 0x033F;
        public const int WM_HANDHELDFIRST = 0x0358;
        public const int WM_HANDHELDLAST = 0x035F;
        public const int WM_AFXFIRST = 0x0360;
        public const int WM_AFXLAST = 0x037F;
        public const int WM_PENWINFIRST = 0x0380;
        public const int WM_PENWINLAST = 0x038F;
        public const int WM_APP = 0x8000;
        public const int WM_USER = 0x0400;
        public const int WM_REFLECT = WM_USER + 0x1C00;

        // 중복 값의 코드는 밑으로 빼놓음
        public const int WM_IME_KEYLAST = 0x010F;
        public const int WM_SETTINGCHANGE = WM_WININICHANGE;
        public const int WM_KEYFIRST = 0x0100;
        public const int WM_MOUSEFIRST = 0x0200;
        public const int WM_KEYLAST = 0x0109;
    }
}
